#!/usr/bin/env python3
"""
Meta-script for running experiment in the `scripts/` directory.

Usage:
    ./run <script> [<args>...]
"""
import sys
from importlib import import_module

if __name__ == "__main__":
    if sys.argv[0] == "./run":
        sys.argv.pop(0)

    to_run = sys.argv[0]

    script = import_module(f"scripts.{to_run}")
    script.run()
